Örnek Teorisi

In [5]:
import numpy as np
populasyon=np.random.randint(0,80,1000)
populasyon[0:10]

array([ 4, 55,  6, 19, 52, 74, 46, 12, 15, 63])

In [8]:
#Örneklem Çekimi
np.random.seed(115) #Her çalıştırdığımızda aynı rastgele sayıları almak için kullanılır
orneklem=np.random.choice(a=populasyon,size=100)  # choice ile populasyon'dan rastgele 100 elemanlı örneklem çektik.
orneklem[0:10]

array([28,  1,  5, 29, 49, 42, 61, 69, 11,  1])

In [9]:
orneklem.mean()

np.float64(38.17)

In [10]:
populasyon.mean()  # Bu ortalamaların birbirine bukadar yakın olması örneklemin gücünü gösterir.

np.float64(38.426)

In [11]:
import seaborn as sns
tips=sns.load_dataset("tips")
df=tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
df.describe().T  #Sayısal değişkenler için kullanılır

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [1]:
!pip install researchpy as rp
%pip install researchpy

zsh:1: command not found: pip
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 7.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 8.4 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [12]:
import researchpy as rp
rp.summary_cont(df[["total_bill","tip","size"]]) #Sürekli değişkenler için
#Sürekli (sayısal) değişkenler için tanımlayıcı istatistikler (descriptive statistics) verir.

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/researchpy/summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'total_bill' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/researchpy/summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'tip' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/researchpy/summary.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'size' has dtype incompatible with float64, plea

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [16]:
rp.summary_cat(df[["sex","smoker","day"]])  #Kategorik değişkenler için   
 #Frekansını (kaç tane var)
 #Yüzdesini
 #Kümülatif yüzdesini hızlıca tablo şeklinde verir.

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [18]:
df[["tip","total_bill"]].cov()        #KOVARYANS: İki değişkenin birlikte nasıl değiştiğini gösterir.                      

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [19]:
df[["tip","total_bill"]].corr()       #KORELASYON: İki değişken arasındaki yönü ve gücü gösterir.

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

In [2]:
import numpy as np
fiyatlar=np.random.randint(10,110,1000)
fiyatlar.mean()

np.float64(59.519)

In [3]:
import statsmodels.stats.api as sms        #statsmodel kütüphanesi istatistiksel testler ve analizler yapmak için kullanılır.  

In [5]:
sms.DescrStatsW(fiyatlar).tconfint_mean() #fiyatlar listesinin ortalaması için %95 güven aralığını hesaplar.
#tconfint_mean: Veri setinin ortalaması için t dağılımına göre %95 güven aralığını hesaplar.
#DescrStatsW:fiyatlar verisi için tanımlayıcı istatistikler (mean, std, var, count vs.) hesaplamaya yarayan bir istatistiksel nesne oluşturur.

(np.float64(57.70265142285219), np.float64(61.335348577147805))

## Bernoulli Dağılımı

Bernoulli dağılımı, yalnızca **iki olasılıklı** (başarı veya başarısızlık) deneylerde kullanılır.

### Olasılık Kütle Fonksiyonu (PMF)

\[
P(X = x) = 
\begin{cases}
p & \text{eğer } x = 1 \ (\text{başarı}) \\
1 - p & \text{eğer } x = 0 \ (\text{başarısızlık})
\end{cases}
\]

Kısa hali:

\[
P(X = x) = p^x (1 - p)^{1 - x}, \quad x \in \{0, 1\}
\]

---

### Beklenen Değer (Ortalama)

\[
E(X) = p
\]

### Varyans

\[
Var(X) = p(1 - p)
\]

---

**Parametreler:**
- \( p \): Başarı olasılığı \((0 \leq p \leq 1)\)
- \( X \): 0 (başarısızlık) veya 1 (başarı) alabilen rassal değişken


In [7]:
from scipy.stats import bernoulli

In [8]:
p=0.6
result=bernoulli(p)           #Dağılımı burada tanımladık
result.pmf(k=0)               #pmf=probability mass function (olasılık kütle fonksyonu) 
#Bernoulli dağılımına göre, 0 (başarısızlık) sonucunun olasılığı nedir? sorusu cevaplanıyor

np.float64(0.3999999999999999)

In [ ]:
Bir rassal değişkenin uzun vadeli kararlığını tanımlayan olasılık teoremidir.

In [2]:
import numpy as np
rng=np.random.RandomState(123) #Rastgele sayı üreticisi (seed) sabitleniyor. Böylece her çalıştırmada aynı rastgele sonuçlar elde edilir.
for i in np.arange(1,21):
    deney_sayisi=2**i
    yazi_turalar=rng.randint(0,2,size=deney_sayisi)     #0 ve 1’den rastgele sayılar üretir. 0 → Tura, 1 → Yazı olarak kabul ediliyor.  
    yazi_olasılıkları=np.mean(yazi_turalar)
    print("Atış Sayısı:",deney_sayisi,"---","Yazı Olasılığı %.2f" % (yazi_olasılıkları*100))

Atış Sayısı: 2 --- Yazı Olasılığı 50.00
Atış Sayısı: 4 --- Yazı Olasılığı 0.00
Atış Sayısı: 8 --- Yazı Olasılığı 62.50
Atış Sayısı: 16 --- Yazı Olasılığı 43.75
Atış Sayısı: 32 --- Yazı Olasılığı 46.88
Atış Sayısı: 64 --- Yazı Olasılığı 56.25
Atış Sayısı: 128 --- Yazı Olasılığı 50.78
Atış Sayısı: 256 --- Yazı Olasılığı 52.73
Atış Sayısı: 512 --- Yazı Olasılığı 52.93
Atış Sayısı: 1024 --- Yazı Olasılığı 50.20
Atış Sayısı: 2048 --- Yazı Olasılığı 48.58
Atış Sayısı: 4096 --- Yazı Olasılığı 49.49
Atış Sayısı: 8192 --- Yazı Olasılığı 49.58
Atış Sayısı: 16384 --- Yazı Olasılığı 49.96
Atış Sayısı: 32768 --- Yazı Olasılığı 50.00
Atış Sayısı: 65536 --- Yazı Olasılığı 49.68
Atış Sayısı: 131072 --- Yazı Olasılığı 49.97
Atış Sayısı: 262144 --- Yazı Olasılığı 50.13
Atış Sayısı: 524288 --- Yazı Olasılığı 50.01
Atış Sayısı: 1048576 --- Yazı Olasılığı 50.09


### Binom Dağılımı

**Tanım:**

Binom dağılımı, sabit sayıda bağımsız denemede, her bir denemede aynı başarı olasılığı ile belirli sayıda başarının gerçekleşme olasılığını verir.

Bir deneme:
- İki olasılıklıdır: **başarı (1)** veya **başarısızlık (0)**  
- Denemeler **birbirinden bağımsızdır**  
- Her denemede başarı olasılığı **aynıdır (p)**  

---

#### Olasılık Kütle Fonksiyonu (PMF):

$$
P(X = k) = \binom{n}{k} \cdot p^k \cdot (1 - p)^{n - k}
$$

Burada:
- \( n \): Deneme sayısı  
- \( k \): Başarı sayısı  
- \( p \): Başarı olasılığı  
- \( \binom{n}{k} \): "n'in k'li kombinasyonu" yani \( \frac{n!}{k!(n - k)!} \)

---

#### Beklenen Değer (Ortalama):

$$
E(X) = n \cdot p
$$

#### Varyans:

$$
Var(X) = n \cdot p \cdot (1 - p)
$$


In [4]:
from scipy.stats import binom

In [5]:
p=0.01
n=100
rv=binom(n,p)
print(rv.pmf(1)) #100 denemede 1 kez başarılı olma olasılığı
print(rv.pmf(10)) #100 denemede 10 kez başarılı olma olasılığı

0.3697296376497269


### Poisson Dağılımı

Poisson dağılımının olasılık kütle fonksiyonu (PMF) şu şekildedir:

$$
P(X = k) = \frac{e^{-\lambda} \cdot \lambda^k}{k!}
$$

Burada:
- \( \lambda \): Belirli bir zaman aralığında beklenen olay sayısı (ortalama)
- \( k \): Olay sayısı (0, 1, 2, ...)
- \( e \): Euler sabiti (yaklaşık 2.718)

---

#### Beklenen Değer (Ortalama):

$$
E(X) = \lambda
$$

#### Varyans:

$$
Var(X) = \lambda
$$


In [8]:
from scipy.stats import poisson

λ=0.1 
rv=poisson(mu=λ)       #ortalama olay sayısı 0.1 olan bir dağılım oluşturuldu.
print(rv.pmf(k=0))
print(rv.pmf(k=5))     #Ortalama olay sayısı 0.1 olan dağılımda olay sayısısının 5 olma olasılığı

0.9048374180359595
7.54031181696634e-08


NORMAL DAĞILIM

Normal dağıldığı bilinen sürekli rassal değişkenler için olasılık hesaplaması için kullanılır.

$$
f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \cdot e^{-\frac{(x - \mu)^2}{2\sigma^2}}
$$

In [10]:
from scipy.stats import norm
#cdf (kümülatif dağılım fonksiyonu) --  Bir rastgele değişkenin belirli bir değere kadar olan tüm olasılıklarının toplamını verir.

1-norm.cdf(90,80,5)  #cdf(a,b,c) a:hesaplanacak değer  b:ortalama  c:standart sapma

np.float64(0.02275013194817921)

In [11]:
1-norm.cdf(70,80,5) #70'den fazla olması olasılığı

np.float64(0.9772498680518208)

In [13]:
norm.cdf(73,80,5) #73'den az olması olasılığı

np.float64(0.08075665923377107)

In [14]:
# 85 ile 90 arasında olması olasılığı
norm.cdf(90,80,5)-norm.cdf(85,80,5)

np.float64(0.13590512198327787)

### Z-Testi Formülü

$$
Z = \frac{\bar{x} - \mu}{\frac{\sigma}{\sqrt{n}}}
$$

- \( \bar{x} \): Örneklem ortalaması  
- \( \mu \): Anakütle ortalaması (hipotezdeki değer)  
- \( \sigma \): Anakütle standart sapması  
- \( n \): Örneklem büyüklüğü
### T-Testi Formülü

$$
t = \frac{\bar{x} - \mu}{\frac{s}{\sqrt{n}}}
$$

- \( \bar{x} \): Örneklem ortalaması  
- \( \mu \): Anakütle ortalaması (hipotezdeki değer)  
- \( s \): Örneklem standart sapması  
- \( n \): Örneklem büyüklüğü

In [3]:
import numpy as np

olcumler = np.array([
    156, 162, 145, 173, 149, 160, 152, 158, 147, 151,
    166, 170, 155, 157, 150, 165, 163, 159, 148, 153,
    172, 161, 167, 164, 154, 169, 168, 146, 174, 175,
    143, 144, 142, 141, 140, 139, 138, 137, 136, 135,
    134, 133, 132, 131, 130, 129, 128, 127, 126, 125
])

olcumler[0:10]

array([156, 162, 145, 173, 149, 160, 152, 158, 147, 151])

In [10]:
import scipy.stats as stats

stats.describe(olcumler)   #ölcumler dizisinin temel tanımlayıcı istatistiklerini hesaplar. 

DescribeResult(nobs=np.int64(50), minmax=(np.int64(125), np.int64(175)), mean=np.float64(149.58), variance=np.float64(216.33020408163267), skewness=np.float64(0.026557413214849248), kurtosis=np.float64(-1.1717982874169544))

In [11]:
#Shapiro-Wilks Testi -->Veri setinin normal dağılıma uygun olup olmadığını test eden istatistiksel bir testtir.

from scipy.stats import shapiro
shapiro(olcumler)

ShapiroResult(statistic=np.float64(0.9586265924822278), pvalue=np.float64(0.07786239988170086))

In [ ]:
#p>0.05 olduğu için h0 hipotezini reddedemiyoruz. Yani elimizdeki olcumler verisi için normal dağılım varsayımı geçerlidir.

In [12]:
stats.ttest_1samp(olcumler,popmean=170) 
#Örneklem ortalaması, verilen popülasyon ortalaması (170) ile istatistiksel olarak aynı mı, 
#farklı mı? bunu test ederiz.

TtestResult(statistic=np.float64(-9.817076153233275), pvalue=np.float64(3.702242889026129e-13), df=np.int64(49))

In [ ]:
#p<0.05 olduğundan H0 red yani veri setinin ortalaması 170 değil.

In [4]:
from statsmodels.stats.descriptivestats import sign_test 
sign_test(olcumler,170) 

(np.float64(-20.5), np.float64(8.225455871979648e-10))

# İŞ Uygulaması: Dönüşüm Oranı Testi  

**Problem:** Bir yazılım ile bir mecrada reklam verilmiş ve bu reklama ilişkin yazılım tarafından 0.125 dönüşüm oranı elde edildiği ifade edilmiş.  
Fakat bu durum kontrol edilmek isteniyor. Çünkü bu yüksek bir oran ve gelirler incelendiğinde örtüşmüyor.  

**Detaylar:** 500 kişi dış mecrada reklamlara tıklamış, 40 tanesi sitemize gelip alışveriş yapmış.  

**Örnek üzerinden elde edilen dönüşüm oranı:**  
\[
\frac{40}{500} = 0.08
\]

**Hipotezler:**  
- \(H_0: p = 0.125\) (gerçek dönüşüm oranı %12.5’tir)  
- \(H_1: p \neq 0.125\) (gerçek dönüşüm oranı %12.5 değildir)  


In [6]:
from statsmodels.stats.proportion import proportions_ztest

In [7]:
count=40     #Başarılı gözlem
nobs=500     #Gözlem Sayısı
value=0.125  #Test etmek istediğimiz değer

In [8]:
proportions_ztest(count,nobs,value)

(np.float64(-3.7090151628513017), np.float64(0.00020806696898459793))